language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - flex
    - valgrind
before_script:
  - lex --version
  - flex --version
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then valgrind --version; fi
script:
  - make
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./test.pl; else ./test.pl --valgrind; fi
