language: c
os: linux
dist: xenial
addons:
  apt:
    packages:
    - flex
    - valgrind
before_script:
  - lex --version
  - flex --version
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then valgrind --version; fi
script: |
  make &&
  ./test.pl --valgrind &&
  make package

jobs:
  include:
    - dist: precise
      compiler: gcc
    - compiler: gcc
    - compiler: clang
    - os: osx
      compiler: clang
      script: make && ./test.pl && make package
