language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
install:
  - .travis/install.sh
before_script:
  - lex --version
  - flex --version
  - valgrind --version
script: make && ./test.pl --valgrind
